name: Fuzz Test

on:
  push:
    branches: main

jobs:
  fuzz-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang llvm git

      - name: Install AFL++
        run: |
          mkdir -p ~/afl
          cd ~/afl
          git clone https://github.com/AFLplusplus/AFLplusplus
          cd AFLplusplus
          make distrib
          sudo make install

      - name: Configure CMake
        run: |
          mkdir -p build
          CC=~/afl/AFLplusplus/afl-clang-fast CXX=~/afl/AFLplusplus/afl-clang-fast++ cmake -B build
  
      - name: Build with CMake
        run: cmake --build build

      - name: Run AFL++ Fuzzer with Workers
        env:
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
        run: |
            afl-fuzz -M master -i ./testcases -o ./fuzz_outputs -- ./build/afldemo @@ &

            afl-fuzz -S worker1 -i ./testcases -o ./fuzz_outputs -- ./build/afldemo @@ &
            wait
      
      - name: Upload Fuzzing Outputs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-outputs
          path: ${{github.workspace}}/fuzz_outputs/